create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table session (
    id bigint generated by default as identity,
    start_time date not null,
    end_time date not null,
    status varchar(255) not null,
    type varchar(255) not null,
    max_capacity int,
    tuition_fee bigint,
    enrollment_status varchar(255) not null,
    primary key (id)
);

create table course_session (
    course_id bigint not null,
    session_id bigint not null,
    primary key (course_id, session_id),
    foreign key (course_id) references course(id),
    foreign key (session_id) references session(id)
);

create table image_cover (
    id bigint generated by default as identity,
    url varchar(2048) not null,
    size int not null,
    type varchar(255) not null,
    width int not null,
    height int not null,
    session_id bigint null,
    primary key (id),
    foreign key (session_id) references session(id)
);

create table participant (
    id bigint generated by default as identity,
    session_id bigint not null,
    user_id bigint not null,
    approval_status varchar(255) not null,
    primary key (id),
    foreign key (session_id) references session(id),
    foreign key (user_id) references ns_user(id),
    unique (session_id, user_id)
);
